// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZNUYYtkN4fErpbRS1GzlW0AblcgK9y4',
    appId: '1:66818701213:web:03d2727082e1408d9f6174',
    messagingSenderId: '66818701213',
    projectId: 'foodies-1c260',
    authDomain: 'foodies-1c260.firebaseapp.com',
    storageBucket: 'foodies-1c260.appspot.com',
    measurementId: 'G-511GPPHTBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8f33I_fmP65SaaHu41X-FOvOfUJf4blQ',
    appId: '1:66818701213:android:6b3dc8ba9033b3109f6174',
    messagingSenderId: '66818701213',
    projectId: 'foodies-1c260',
    storageBucket: 'foodies-1c260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB55bh7uGMQQl1XT0BiDmjukybTkPTULs',
    appId: '1:66818701213:ios:d21a21507b9543c19f6174',
    messagingSenderId: '66818701213',
    projectId: 'foodies-1c260',
    storageBucket: 'foodies-1c260.appspot.com',
    iosBundleId: 'com.example.foodies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB55bh7uGMQQl1XT0BiDmjukybTkPTULs',
    appId: '1:66818701213:ios:d21a21507b9543c19f6174',
    messagingSenderId: '66818701213',
    projectId: 'foodies-1c260',
    storageBucket: 'foodies-1c260.appspot.com',
    iosBundleId: 'com.example.foodies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADZNUYYtkN4fErpbRS1GzlW0AblcgK9y4',
    appId: '1:66818701213:web:ee5f46d162535f829f6174',
    messagingSenderId: '66818701213',
    projectId: 'foodies-1c260',
    authDomain: 'foodies-1c260.firebaseapp.com',
    storageBucket: 'foodies-1c260.appspot.com',
    measurementId: 'G-WYZDYB282B',
  );
}
